
name: Build docker container

inputs:
  container_context:
    type: string
    required: true
    default: container
  container_tag:
    type: string
    required: true
    default: maya/build_document:test

runs:
  using: "composite"
  steps:
    - name: Set up Docker buildx
      uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

    - name: Build Docker container
      uses: docker/build-push-action@14487ce63c7a62a4a324b0bfb37086795e31c6c1 # v6.16.0
      with:
        context: ${{ inputs.container_context }}
        load: true
        tags: ${{ inputs.container_tag }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
