
name: Release

on:
  workflow_call:
    inputs:
      container_context:
        type: string
        required: true
        default: container
      container_tag:
        type: string
        required: true
        default: maya/build_document:test

jobs:
  build_container:
    name: Build docker container
    steps:
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker container
        uses: docker/build-push-action@v2
        with:
          context: ${{ inputs.container_context }}
          load: true
          tags: ${{ inputs.container_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
