
name: Release

on:
  workflow_dispatch:
  
env:
  CONTAINER_TAG: maya/build_document:test
  CONTAINER_SOURCE_PATH: /opt/source
  CONTAINER_BUILD_PATH: /opt/source/build
  CONTAINER_MAIN_PATH: main.tex
  DOCUMENT_BASE_NAME: "The Decipherment of the Maya Hieroglyphs"
  SOURCE_BUNDLE_NAME: sources.zip

jobs:
  create_release_draft:
    name: Create release draft
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Bundle sources
        run: zip -r ${{ env.SOURCE_BUNDLE_NAME }} . -x ".git/*"
      
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build Docker container
        uses: docker/build-push-action@v2
        with:
          context: container
          load: true
          tags: ${{ env.CONTAINER_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Determine version
        id: determine_version
        run: >-
          echo "release_version=
          $(docker run --rm 
          -v $GITHUB_WORKSPACE:${{ env.CONTAINER_SOURCE_PATH }}
          ${{ env.CONTAINER_TAG }}
          pwsh -Command "${{ env.CONTAINER_SOURCE_PATH }}/Edit-DocumentVersion.ps1 
          -VersionTexPath ${{ env.CONTAINER_SOURCE_PATH }}/document-version.tex 
          -LongCount 
          ")" 
          >> $GITHUB_OUTPUT

      - name: Define document name
        id: define_document_name
        run: >-
          echo "document_name=
          ${{ env.DOCUMENT_BASE_NAME }}(${{ steps.determine_version.outputs.release_version }}) 
          >> $GITHUB_OUTPUT

      - name: Compile document
        run: >-
          docker run --rm 
          -v $GITHUB_WORKSPACE:${{ env.CONTAINER_SOURCE_PATH }}
          -v $GITHUB_WORKSPACE/build:${{ env.CONTAINER_BUILD_PATH }}
          ${{ env.CONTAINER_TAG }}
          pwsh -Command "${{ env.CONTAINER_SOURCE_PATH }}/Compile-Document.ps1
          -SourcePath \"${{ env.CONTAINER_SOURCE_PATH }}\" 
          -BuildPath \"${{ env.CONTAINER_BUILD_PATH}}\" 
          -DocumentName \"${{ steps.define_document_name.outputs.document_name }}\" 
          -TexFile \"${{ env.CONTAINER_MAIN_PATH }}\""

      - name: Create tag
        run: |
          git tag ${{ steps.determine_version.outputs.release_version }} HEAD
          git push origin ${{ steps.determine_version.outputs.release_version }}

      - name: Create release draft
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          prerelease: false
          name: ${{ steps.determine_version.outputs.release_version }}
          tag: ${{ steps.determine_version.outputs.release_version }}
          bodyFile: CHANGELOG.md
          artifacts: |
            "build/${{ steps.define_document_name.outputs.document_name }}.pdf
            ${{ env.SOURCE_BUNDLE_NAME }}"

