
name: Release

on:
  workflow_dispatch:
  
env:
  CONTAINER_BUILD_PATH: /opt/source/build
  CONTAINER_MAIN_PATH: /opt/source/main.tex
  DOCUMENT_BASE_NAME: "The Decipherment of the Maya Hieroglyphs"
  SOURCE_BUNDLE_NAME: sources.zip

jobs:
  create_release_draft:
    name: Create release draft
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Build Docker container
        uses: ./.github/actions/docker_build

      - name: Bundle sources
        run: zip -r ${{ env.SOURCE_BUNDLE_NAME }} . -x ".git/*"

      - name: Determine version
        id: determine_version
        uses: ./.github/actions/docker_run
        with:
          return_value: true
          command: >-
            ${{ env.CONTAINER_SOURCE_PATH }}/Edit-DocumentVersion.ps1 
            -VersionTexPath ${{ env.CONTAINER_SOURCE_PATH }}/document-version.tex 
            -LongCount

      - name: Define document name
        id: document_name
        run: >-
          echo "value=
          ${{ env.DOCUMENT_BASE_NAME }}(${{ steps.release_version.outputs.value }}) 
          >> $GITHUB_OUTPUT

      - name: Compile document
        uses: ./.github/actions/docker_run
        with:
          command: >-
            ${{ env.CONTAINER_SOURCE_PATH }}/Compile-Document.ps1
            -TexPath \"${{ env.CONTAINER_MAIN_PATH }}\""
            -BuildPath \"${{ env.CONTAINER_BUILD_PATH}}\" 
            -DocumentName \"${{ steps.document_name.outputs.value }}\" 

      - name: Create tag
        run: |
          git tag ${{ steps.release_version.outputs.value }} HEAD
          git push origin ${{ steps.release_version.outputs.value }}

      - name: Create release draft
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          prerelease: false
          name: ${{ steps.release_version.outputs.value }}
          tag: ${{ steps.release_version.outputs.value }}
          bodyFile: CHANGELOG.md
          artifacts: |
            "build/${{ steps.document_name.outputs.value }}.pdf
            ${{ env.SOURCE_BUNDLE_NAME }}"

